# Config file

# General
debug-mode: true

# Base de Datos
database-url: ""
database-username: ""
database-password: ""

database-driver: "org.mariadb.jdbc.Driver"
database-show-sql: "false"
database-current-session-context-class: "thread"
