# Config file

# General
debug-mode: true

# Base de Datos
database-url: ""
database-username: ""
database-password: ""

database-driver: "org.mariadb.jdbc.Driver"
database-show-sql: "false"
database-current-session-context-class: "thread"

# Discord
discord-bot-token: ""
discord-interaction-expiration: 15 # Cada cuantos minutos expiran las interacciones de Discord.

discord-staff-guild-id:  # ID del servidor del Staff Hub.
discord-staff-log-id:  # ID del canal de Discord donde se enviarán los logs del staff.
discord-staff-console-log-id:  # ID del canal de Discord donde se enviarán los logs de la consola del servidor.
discord-dev-role-id:  # ID del rol de Discord que identifica a los desarrolladores.

discord-global-chat: true # Habilitar chat global entre servidor y Discord.
discord-country-chat: true # Habilitar chat por país entre servidor y Discord.
discord-staff-log: true # Habilitar logs de acciones en el Staff Hub.
discord-staff-console-log: true # Habilitar logs de la consola del servidor en el Staff Hub.

discord-player-join-leave: true # Habilitar mensajes de entrada y salida de jugadores en Discord. Depende de discord-country-chat y/o discord-global-chat para mostrarse en Discord.
discord-player-join-leave-chat: true # Habilitar mensajes de entrada y salida del chat de jugadores en Discord. Depende de discord-country-chat y/o discord-global-chat para mostrarse en Discord.
discord-server-start-stop: true # Habilitar mensajes de inicio y stop del servidor en Discord. Depende de discord-country-chat para mostrarse en Discord.

# World
tp-cooldown-seconds: 5
layer-1-offset: 1700
layer-2-offset: 5500

# Commands
# Cooldowns por comando (En segundos). En caso de no especificar, se usa el valor por defecto. 
# Nota: El cooldown es por cada comando/subcomando. Es decir, si se especifica un cooldown para "btecs" y otro para "btecs test", ambos se aplican independientemente.
# Por lo que el cooldown de btecs no afecta al de btecs test y el resto de subcomandos. 

default-cooldown: 5
commands-cooldowns:
  btecs: 10
  btecs.test: 200

# Configuración de Players
player-defaults:
  general:
    global-chat-on-join: true
  reviewer:
    notifications: true
  manager:
    notifications: true