# Config file

# General
debug-mode: true
interaction-expiration: 15 # Cada cuantos minutos se revisa las interacciones expiradas.
interaction-expirations:
  join-project: 1440 # Expiración de solicitudes de unión a proyectos (en minutos). 1440 = 1 día.
  finish-project: 1440 # Expiración de solicitudes de finalización de proyectos (en minutos). 1440 = 1 día.
  finish-edit-project: 1440 # Expiración de solicitudes de finalización de edición de proyectos (en minutos). 1440 = 1 día.
  redefine-project: 1440 # Expiración de solicitudes de redefinición de proyectos (en minutos). 1440 = 1 día.
  create-project: 10080 # Expiración de solicitudes de creación de proyectos (en minutos). 10080 = 7 días.
  accept-reject-create-project: 60 # Expiración del modal de aceptación/rechazo de creación de proyecto (en minutos). 60 = 1 hora.
  accept-reject-redefine-project: 60 # Expiración del modal de aceptación/rechazo de redefinición de proyecto (en minutos). 60 = 1 hora.
default-language: "SPANISH" # Lenguaje por defecto para los jugadores que no tengan uno configurado o cuyo lenguaje configurado no esté soportado.
avatar-url: "https://cravatar.eu/helmavatar/%uuid%/190.png"
max-offline-players-list: 2000 # Cantidad máxima de jugadores offline a mostrar en la lista de jugadores.
# Map Sat
map-padding: 0.005
map-link: "https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/%geojson%/[%minLon%,%minLat%,%maxLon%,%maxLat%]/800x600?attribution=false&logo=false&access_token=%token%"
mapbox-month-limit: 45000 # Límite mensual de requests a MapBox.
map:
  border-width: 2 # Ancho del borde de los proyectos en el mapa.
  border-opacity: 0.8 # Opacidad del borde de los proyectos en el mapa. (0.0 - 1.0)
  fill-opacity: 0.3 # Opacidad del relleno de los proyectos en el mapa. (0.0 - 1.0)
  padding: 0.005
  project:
    fill-color: "#5742DE" # Color del proyecto en el mapa.
    border-color: "#5742DE" # Color del borde del proyecto en el mapa.
  others-projects:
    fill-color: "#42DE57" # Color de los otros proyectos en el mapa.
    border-color: "#42DE57" # Color del borde de los otros proyectos en el mapa.
  redefine:
    fill-color: "#DE5742" # Color de la redefinición en el mapa.
    border-color: "#DE5742" # Color del borde de la redefinición en el mapa.
# Base de Datos
database-driver: "org.mariadb.jdbc.Driver"
database-show-sql: "false"
database-current-session-context-class: "thread"

# Discord
discord-global-chat: true # Habilitar chat global entre servidor y Discord.
discord-country-chat: true # Habilitar chat por país entre servidor y Discord.
discord-country-log: true # Habilitar logs de acciones de proyectos por país. 
discord-staff-log: true # Habilitar logs de acciones de proyectos en el Staff Hub.
discord-staff-console-log: true # Habilitar logs de la consola del servidor en el Staff Hub.

discord-player-join-leave: true # Habilitar mensajes de entrada y salida de jugadores en Discord. Depende de discord-country-chat y/o discord-global-chat para mostrarse en Discord.
discord-player-join-leave-chat: true # Habilitar mensajes de entrada y salida del chat de jugadores en Discord. Depende de discord-country-chat y/o discord-global-chat para mostrarse en Discord.
discord-server-start-stop: true # Habilitar mensajes de inicio y stop del servidor en Discord. Depende de discord-country-chat para mostrarse en Discord.

# World
tp-cooldown-seconds: 5
layers:
  capa_baja:
    name: "capa_1"
    display-name: "Capa Baja"
    offset: 1700
  capa_alta:
    name: "capa_2"
    display-name: "Capa Alta"
    offset: 5500

min-height: -2032
max-height: 2032

wg-proyecto-prefix: "proyecto_" # Prefijo para las regiones de los proyectos en WorldGuard.
wg-parent-proyecto: "proyectos"

border-particles:
  pais-enable: true # Habilitar partículas para los bordes de los países.
  label-enable: true # Habilitar partículas para los bordes de las etiquetas.
  project-enable: true # Habilitar partículas para los bordes de los proyectos.
  pais-particle: "VILLAGER_HAPPY" # Tipo de partícula que no requiera datos adicionales (https://jd.papermc.io/paper/1.21.11/org/bukkit/Particle.html)
  label-particle: "CLOUD" # Tipo de partícula que no requiera datos adicionales (https://jd.papermc.io/paper/1.21.11/org/bukkit/Particle.html)
  project-particle: "FLAME" # Tipo de partícula que no requiera datos adicionales (https://jd.papermc.io/paper/1.21.11/org/bukkit/Particle.html)
  max-distance: 50.0 # Distancia máxima desde el jugador para renderizar partículas
  layers: 21 # Número de capas verticales de partículas
  spawn-period: 20 # Cada cuántos ticks se spawnean las partículas (20 ticks = 1 segundo)

world-edit:
  region-select-extension: 10 # Cantidad de bloques que se extiende verticalmente (arriba y abajo) la selección al usar /project select para seleccionar un proyecto.

banned-items:
  - "OAK_BOAT"
  - "SPRUCE_BOAT"
  - "BIRCH_BOAT"
  - "JUNGLE_BOAT"
  - "ACACIA_BOAT"
  - "DARK_OAK_BOAT"
  - "MANGROVE_BOAT"
  - "CHERRY_BOAT"
  - "BAMBOO_RAFT"
  - "OAK_CHEST_BOAT"
  - "SPRUCE_CHEST_BOAT"
  - "BIRCH_CHEST_BOAT"
  - "JUNGLE_CHEST_BOAT"
  - "ACACIA_CHEST_BOAT"
  - "DARK_OAK_CHEST_BOAT"
  - "MANGROVE_CHEST_BOAT"
  - "CHERRY_CHEST_BOAT"
  - "BAMBOO_CHEST_RAFT"

# Cooldowns por comando (En segundos). En caso de no especificar, se usa el valor por defecto. 
# Nota: El cooldown es por cada comando/subcomando. Es decir, si se especifica un cooldown para "btecs" y otro para "btecs test", ambos se aplican independientemente.
# Por lo que el cooldown de btecs no afecta al de btecs test y el resto de subcomandos. 

default-cooldown: 5
commands-cooldowns:
  btecs: 10
  btecs.test: 200

commands-aliases:
  btecs:
    aliases: ["bteconosur"]
    test:
      aliases: ["t", "ts", "tst"]
      simplemenu.aliases: ["menusimple", "menu"]
  project:
    aliases: ["proyecto", "p"]
    accept.aliases: ["aceptar"]
  pais:
    aliases: ["paisprefix", "prefix"]
# Configuración de Players
player-defaults:
  general:
    global-chat-on-join: true
    simultaneous-notifications: true
    pais-border: true
    label-border: true
  reviewer:
    ds-notifications: true
  manager:
    ds-notifications: true

# Configuración de Proyectos
max-members-for-postulantes: 1 # Cantidad máxima de miembros que un usuario con rango Postulante puede agregar a sus proyectos.